"""Run a stored LeetCode solution against the problem's own example inputs.

Auto-generated by leetvault - do not edit; it is rewritten on sync.

Usage:
    python leetvault_runner.py Problems/two-sum
    python Problems/two-sum/run.py          # equivalent, from anywhere

Prints your solution's output for each example. It does *not* assert correctness:
LeetCode's API exposes example *inputs* but not their expected outputs (those exist only
in the prose of the problem statement), so any pass/fail verdict here would be guesswork.
Compare against the "Output:" lines in that problem's question.md.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

# LeetCode's judge preloads a large namespace into every submission, so stored solutions
# routinely use `List[int]`, `gcd(...)` or `bisect_left(...)` with no import at all.
# Executing such a file as-is raises NameError, so the same names are rebuilt here.
import bisect  # noqa: F401
import collections  # noqa: F401
import functools  # noqa: F401
import heapq  # noqa: F401
import itertools  # noqa: F401
import math  # noqa: F401
import re  # noqa: F401
import string  # noqa: F401
from bisect import bisect, bisect_left, bisect_right, insort  # noqa: F401
from collections import Counter, OrderedDict, defaultdict, deque  # noqa: F401
from functools import cache, cmp_to_key, lru_cache, reduce  # noqa: F401
from heapq import heapify, heappop, heappush, heappushpop, nlargest, nsmallest  # noqa: F401
from itertools import accumulate, combinations, permutations, product  # noqa: F401
from math import ceil, comb, factorial, floor, gcd, inf, isqrt, lcm, perm, sqrt  # noqa: F401
from typing import Deque, Dict, List, Optional, Set, Tuple  # noqa: F401,UP035


class ListNode:
    """LeetCode's singly-linked list node."""

    def __init__(self, val: int = 0, next: "ListNode | None" = None) -> None:
        self.val = val
        self.next = next


class TreeNode:
    """LeetCode's binary tree node."""

    def __init__(
        self, val: int = 0, left: "TreeNode | None" = None, right: "TreeNode | None" = None
    ) -> None:
        self.val = val
        self.left = left
        self.right = right


def _build_namespace() -> dict[str, Any]:
    """Everything LeetCode's judge makes available without an import."""
    names: dict[str, Any] = {
        "ListNode": ListNode,
        "TreeNode": TreeNode,
        "inf": inf,
    }
    for obj in (
        List, Dict, Set, Tuple, Optional, Deque,
        Counter, OrderedDict, defaultdict, deque,
        bisect_left, bisect_right, insort,
        cache, cmp_to_key, lru_cache, reduce,
        heapify, heappop, heappush, heappushpop, nlargest, nsmallest,
        accumulate, combinations, permutations, product,
        ceil, comb, factorial, floor, gcd, isqrt, lcm, perm, sqrt,
    ):
        name = getattr(obj, "__name__", None) or getattr(obj, "_name", None)
        if name:
            names[name] = obj

    # Bind module names last and from sys.modules: `from bisect import bisect` above binds
    # the *function* to the name `bisect`, which would otherwise shadow the module and
    # break any solution calling `bisect.bisect_right(...)`.
    for module_name in (
        "bisect", "collections", "functools", "heapq", "itertools", "math", "re", "string",
    ):
        names[module_name] = sys.modules[module_name]
    # Optional third-party module LeetCode also provides; absent locally unless installed.
    try:
        import sortedcontainers  # noqa: F401

        names["SortedList"] = sortedcontainers.SortedList
        names["SortedDict"] = sortedcontainers.SortedDict
        names["SortedSet"] = sortedcontainers.SortedSet
    except ImportError:
        pass
    return names


_PRELOADED: dict[str, Any] = _build_namespace()

# Types LeetCode encodes as plain JSON, so an example input decodes straight into the
# argument. Anything else (ListNode, TreeNode, ...) needs real construction and is refused
# rather than silently mis-run.
_SCALAR_TYPES = {"integer", "long", "double", "float", "string", "boolean", "character"}


def _is_json_type(type_name: str) -> bool:
    """True for scalars and any nesting of them: `integer[]`, `character[][]`,
    `list<list<string>>` and so on."""
    t = type_name.strip().lower()
    while True:
        if t in _SCALAR_TYPES:
            return True
        if t.endswith("[]"):
            t = t[:-2].strip()
            continue
        if t.startswith("list<") and t.endswith(">"):
            t = t[5:-1].strip()
            continue
        return False


def _load_solution(problem_dir: Path) -> Any:
    """exec the stored solution with LeetCode's implicit names available."""
    candidates = sorted(problem_dir.glob("latest.*"))
    if not candidates:
        raise SystemExit(f"no latest.* solution file in {problem_dir}")
    source_path = candidates[0]
    if source_path.suffix != ".py":
        raise SystemExit(
            f"{source_path.name} is not Python; this runner only executes Python solutions."
        )

    namespace: dict[str, Any] = dict(_PRELOADED)
    namespace["__name__"] = "leetvault_solution"
    exec(compile(source_path.read_text(encoding="utf-8"), str(source_path), "exec"), namespace)

    solution_cls = namespace.get("Solution")
    if solution_cls is None:
        raise SystemExit(f"{source_path.name} defines no `Solution` class.")
    return solution_cls()


def _parse_cases(raw: str, param_count: int) -> list[list[Any]]:
    lines = [ln for ln in raw.splitlines() if ln.strip() != ""]
    if param_count <= 0 or len(lines) % param_count != 0:
        return []
    cases: list[list[Any]] = []
    for i in range(0, len(lines), param_count):
        chunk = lines[i : i + param_count]
        try:
            cases.append([json.loads(v) for v in chunk])
        except json.JSONDecodeError:
            return []
    return cases


def run(problem_dir: Path) -> int:
    metadata_path = problem_dir / "metadata.json"
    if not metadata_path.exists():
        raise SystemExit(f"no metadata.json in {problem_dir}")
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))

    runner_info = metadata.get("runner") or {}
    method_name = runner_info.get("method")
    params = runner_info.get("param_types") or []
    raw_cases = runner_info.get("example_testcases") or ""

    print(f"{metadata.get('frontend_id')}. {metadata.get('title')}  [{metadata.get('difficulty')}]")
    judged = metadata.get("total_testcases")
    if judged:
        print(
            f"Accepted on LeetCode against {metadata.get('total_correct')}/{judged} judge "
            "test cases (only the examples below are available locally)."
        )
    print("-" * 60)

    if not method_name:
        print("This problem has no single entry point (a design/interactive problem),")
        print("so it can't be driven automatically. Run it manually instead.")
        return 0

    unsupported = [t for t in params if not _is_json_type(t)]
    if unsupported:
        print(f"Parameter type(s) {unsupported} need custom construction")
        print("(e.g. linked lists or trees), so inputs can't be built automatically.")
        print(f"Call Solution().{method_name}(...) yourself with the inputs you want.")
        return 0

    cases = _parse_cases(raw_cases, len(params))
    if not cases:
        print("No usable example inputs were stored for this problem.")
        return 0

    solution = _load_solution(problem_dir)
    method = getattr(solution, method_name, None)
    if method is None:
        print(f"Your solution has no method named `{method_name}`.")
        return 1

    for i, args in enumerate(cases, start=1):
        rendered = ", ".join(json.dumps(a) for a in args)
        try:
            result = method(*args)
        except NameError as exc:
            # Some problems depend on an interface class that exists only inside
            # LeetCode's judge (NestedInteger, Robot, ...). There's nothing to run
            # against locally, so say that plainly instead of repeating it per example.
            print(f"  {exc}")
            print("  This problem relies on a class that only exists in LeetCode's")
            print("  judge, so it can't be run outside LeetCode.")
            return 0
        except Exception as exc:  # noqa: BLE001 - report, don't crash the whole run
            print(f"Example {i}: {rendered}")
            print(f"  raised {type(exc).__name__}: {exc}\n")
            continue
        print(f"Example {i}: {rendered}")
        print(f"  -> {result!r}\n")

    print("Expected outputs are in question.md (LeetCode's API doesn't expose them).")
    return 0


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 1
    return run(Path(argv[1]).resolve())


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
