"""The `leetvault analyze` command: redo an analysis with a different model.

Sync only ever fills gaps - it skips any problem that already has an `analysis.md`, which
is what makes a backfill resumable. That leaves no way to replace an analysis you are not
happy with, and because a free tier's daily quota can stop a backfill part-way, a repo
easily ends up split across several models of differing quality. This command is the
deliberate counterpart: it overwrites on purpose, one problem, one provider's output, or
everything.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

import typer
from rich.console import Console
from rich.progress import BarColumn, Progress, SpinnerColumn, TextColumn, TimeElapsedColumn
from rich.table import Table
from sqlalchemy import select
from sqlalchemy.orm import Session, sessionmaker

from leetvault.client import ProblemMeta
from leetvault.config import ConfigStore
from leetvault.db import make_engine, make_session_factory, session_scope
from leetvault.git_writer import analysis_md_path, question_md_path, write_analysis_md
from leetvault.models import Problem

# Matches the footer write_analysis_md emits, which is the only record of which model wrote
# a given file - the database deliberately stores nothing about generated analysis.
_FOOTER = re.compile(r"^_Generated by leetvault using ([^\s(]+)(?: \(([^)]+)\))?_$", re.MULTILINE)


@dataclass
class AnalysisRow:
    frontend_id: int
    title: str
    title_slug: str
    difficulty: str
    paid_only: bool
    url: str
    topics: list[str]
    provider: str | None
    model: str | None

    @property
    def meta(self) -> ProblemMeta:
        return ProblemMeta(
            question_id=0,
            frontend_id=self.frontend_id,
            title=self.title,
            title_slug=self.title_slug,
            difficulty=self.difficulty,
            paid_only=self.paid_only,
            url=self.url,
        )


def existing_provider(path: Path) -> tuple[str | None, str | None]:
    """Which provider and model wrote an analysis, read back from its footer."""
    if not path.exists():
        return None, None
    match = _FOOTER.search(path.read_text(encoding="utf-8"))
    if match is None:
        return None, None
    return match.group(1), match.group(2)


def _rows(factory: sessionmaker[Session], repo_path: Path) -> list[AnalysisRow]:
    with session_scope(factory) as session:
        problems = sorted(session.scalars(select(Problem)), key=lambda p: p.frontend_id)
        rows = []
        for problem in problems:
            provider, model = existing_provider(analysis_md_path(repo_path, problem.title_slug))
            rows.append(
                AnalysisRow(
                    frontend_id=problem.frontend_id,
                    title=problem.title,
                    title_slug=problem.title_slug,
                    difficulty=problem.difficulty,
                    paid_only=problem.paid_only,
                    url=problem.url,
                    topics=[t.name for t in problem.topics],
                    provider=provider,
                    model=model,
                )
            )
    return rows


def _select(
    rows: list[AnalysisRow], target: str | None, all_: bool, from_: str | None
) -> list[AnalysisRow]:
    if all_:
        return rows
    if from_:
        wanted = from_.strip().lower()
        return [r for r in rows if (r.provider or "").lower() == wanted]
    if target is None:
        return []
    needle = target.strip().lower()
    exact = [r for r in rows if r.title_slug.lower() == needle or str(r.frontend_id) == needle]
    if exact:
        return exact
    return [r for r in rows if needle in r.title.lower() or needle in r.title_slug.lower()]


def _print_listing(console: Console, rows: list[AnalysisRow]) -> None:
    table = Table(title="Analyses by model")
    table.add_column("#", justify="right")
    table.add_column("Problem")
    table.add_column("Generated by")
    for row in rows:
        written_by = row.provider or "[dim]-[/dim]"
        if row.provider and row.model:
            written_by = f"{row.provider} [dim]({row.model})[/dim]"
        table.add_row(str(row.frontend_id), row.title, written_by)
    console.print(table)
    counts: dict[str, int] = {}
    for row in rows:
        counts[row.provider or "(none)"] = counts.get(row.provider or "(none)", 0) + 1
    summary = ", ".join(f"{n} by {name}" for name, n in sorted(counts.items()))
    console.print(f"\n{len(rows)} problem(s): {summary}")


def run_analyze(
    console: Console,
    *,
    target: str | None,
    provider_name: str | None,
    model: str | None,
    all_: bool,
    from_: str | None,
    show_list: bool,
    assume_yes: bool,
) -> None:
    from leetvault.ai import build_user_prompt, compose_analysis, get_provider
    from leetvault.sync import (
        _latest_solution_source,
        _maybe_push_to_github,
        _regenerate_readme,
    )

    store = ConfigStore()
    repo_path = store.resolved_repo_path()
    factory = make_session_factory(make_engine(store.resolved_db_path()))
    rows = _rows(factory, repo_path)

    if not rows:
        console.print("[yellow]No problems in the database yet. Run `leetvault import`.[/yellow]")
        return

    if show_list:
        _print_listing(console, rows)
        return

    if not (target or all_ or from_):
        console.print(
            "[red]Nothing selected.[/red] Name a problem, or use --all, --from <provider>, "
            "or --list."
        )
        raise typer.Exit(code=1)

    selected = _select(rows, target, all_, from_)
    if not selected:
        if from_:
            console.print(f"[yellow]No analysis was generated by {from_!r}.[/yellow]")
        else:
            console.print(f"[yellow]No problem matches {target!r}.[/yellow]")
        return

    chosen = provider_name or store.get("ai_provider")
    if not chosen:
        console.print("[red]No AI provider configured.[/red] Run `leetvault ai` first.")
        raise typer.Exit(code=1)
    provider = get_provider(str(chosen), model or store.get("ai_model"))
    if provider is None:
        console.print(f"[red]Unknown AI provider {chosen!r}.[/red]")
        raise typer.Exit(code=1)

    replacing = [r for r in selected if r.provider]
    if replacing and not assume_yes:
        console.print(
            f"This overwrites [bold]{len(replacing)}[/bold] existing analysis file(s) "
            f"with output from [bold]{chosen}[/bold]. The current text is not recoverable "
            "except from git history."
        )
        for row in replacing[:5]:
            console.print(f"  {row.frontend_id}. {row.title} [dim](now: {row.provider})[/dim]")
        if len(replacing) > 5:
            console.print(f"  [dim]... and {len(replacing) - 5} more[/dim]")
        if not typer.confirm("Continue?", default=False):
            console.print("Nothing changed.")
            return

    written = 0
    failed = 0
    last_error: str | None = None
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        task = progress.add_task(f"Re-analysing via {chosen}", total=len(selected))
        for row in selected:
            with session_scope(factory) as session:
                problem = session.scalars(
                    select(Problem).where(Problem.title_slug == row.title_slug)
                ).first()
                question_id = problem.question_id if problem else None
            solution = (
                _latest_solution_source(factory, question_id) if question_id is not None else None
            )
            if solution is None:
                progress.advance(task)
                continue
            lang, code = solution
            q_path = question_md_path(repo_path, row.title_slug)
            statement = q_path.read_text(encoding="utf-8") if q_path.exists() else ""

            result = compose_analysis(
                provider,
                build_user_prompt(row.title, row.difficulty, row.topics, statement, lang, code),
            )
            body = result.body
            if body:
                # Only replace once the new analysis is in hand and looks real; a failed
                # regeneration must leave the previous file intact rather than deleting it
                # and writing nothing.
                write_analysis_md(repo_path, row.meta, body, str(chosen), provider.model)
                written += 1
            else:
                failed += 1
                last_error = result.error or provider.last_error or last_error
            progress.advance(task)

    if written:
        console.print(f"[green]Rewrote {written} analysis file(s) using {chosen}.[/green]")
    if failed:
        console.print(f"[yellow]{failed} problem(s) produced no analysis; kept the old one.")
        if last_error:
            console.print(f"  [dim]{chosen}:[/dim] {last_error}")
    if not written:
        return

    _regenerate_readme(factory, repo_path)
    _maybe_push_to_github(
        console, repo_path, f"leetvault: re-analyse {written} problem(s) using {chosen}"
    )
